---
# tasks file for ucsdlib.fits

- name: Install Dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - unzip
  become: true

- name: Download fits
  unarchive:
    src: http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_version }}.zip
    copy: no
    dest: '{{ fits_install }}'
    creates: '{{ fits_install }}/fits-{{ fits_version }}/fits.sh'
  become: true

- name: Set Default Symlink
  file:
    path: '{{ fits_install }}/fits'
    src: fits-{{ fits_version }}
    state: link
  become: true
  ignore_errors: '{{ ansible_check_mode }}'
