---
# tasks file for ucsdlib.fits

- name: Install Dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - unzip

- name: Download fits
  unarchive:
    src: https://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_version }}.zip
    copy: no
    dest: '{{ fits_install }}'
    creates: '{{ fits_install }}/fits-{{ fits_version }}/fits.sh'

- name: Set Default Symlink
  file:
    path: '{{ fits_install }}/fits'
    src: fits-{{ fits_version }}
    state: link
  ignore_errors: '{{ ansible_check_mode }}'

- name: Ensure fits is executable
  file:
    path: '{{ fits_install }}/fits-{{ fits_version }}/fits.sh'
    state: file
    mode: "0755"

- name: Disable Tika
  lineinfile:
    dest='{{ fits_install }}/fits-{{ fits_version }}/xml/fits.xml'
    regexp='.*(<.*edu.harvard.hul.ois.fits.tools.tika.TikaTool.*>).*'
    backrefs=yes
    line='<!-- \1 -->'
    state=present
  when: fits_disable_tika
